version: "3.9"

networks:
  order_web:
    name: app_order_web
    driver: overlay
    attachable: true

  order_intercom:
    name: app_order_intercom
    driver: overlay
    attachable: true

volumes:
  order_pg_vol:
  minio_vol:

secrets:
  postgres_user:
    file: docker/postgres_user_secret
  postgres_password:
    file: docker/postgres_password_secret
  s3_user:
    file: docker/s3_user_secret
  s3_password:
    file: docker/s3_password_secret

services:

  traefik:
    image: traefik:v3.6.1
    command:
      - --api.dashboard=true
      - --log.level=DEBUG
      - --providers.swarm=true
      - --providers.swarm.watch=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.network=app_order_web
      - --entrypoints.web.address=:80
    ports:
      - target: 80
        published: 80
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - order_web
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)
        - traefik.http.routers.dashboard.entrypoints=web
        - traefik.http.routers.dashboard.service=api@internal

  frontend:
    image: ghcr.io/ddibiasi/sbd-ais-exercise/frontend:1.0
    networks:
      - order_web
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`localhost`)
        - traefik.http.routers.frontend.entrypoints=web
        - traefik.http.services.frontend.loadbalancer.server.port=80

  orderservice:
    image: ghcr.io/ddibiasi/sbd-ais-exercise/orderservice:1.0
    command: ["/app/ordersystem"]
    depends_on:
      - postgres
      - minio
    secrets:
      - postgres_user
      - postgres_password
      - s3_user
      - s3_password
    environment:
      - POSTGRES_DB=order
      - PGPORT=5555
      - DB_HOST=postgres
      - S3_ENDPOINT=minio:8500
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - S3_ACCESS_KEY_ID_FILE=/run/secrets/s3_user
      - S3_SECRET_ACCESS_KEY_FILE=/run/secrets/s3_password
    networks:
      - order_web
      - order_intercom
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.orders.rule=Host(`orders.localhost`)
        - traefik.http.routers.orders.entrypoints=web
        - traefik.http.services.orders.loadbalancer.server.port=3000

  postgres:
    image: postgres:18
    volumes:
      - order_pg_vol:/var/lib/postgresql
    networks:
      - order_intercom
    secrets:
      - postgres_user
      - postgres_password
    environment:
      - POSTGRES_DB=order
      - PGPORT=5555
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    deploy:
      placement:
        constraints:
          - node.role == manager

  minio:
    image: minio/minio:latest
    command: ["server", "--address", ":8500", "--console-address", ":8501", "/data"]
    volumes:
      - minio_vol:/data
    secrets:
      - s3_user
      - s3_password
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/s3_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/s3_password
    networks:
      - order_intercom
      - order_web
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio.rule=Host(`minio.localhost`)
        - traefik.http.routers.minio.entrypoints=web
        - traefik.http.services.minio.loadbalancer.server.port=8500